import { CheckCircle2, Circle } from "lucide-react";
import { useDashboard } from "../../context/DashboardContext";
import { useSetup } from "../../hooks/useWorkspaceData";

export function SetupTab() {
  const { repoName } = useDashboard();
  const { data, isLoading } = useSetup(repoName || null);
  if (isLoading || !data) return <div className="p-5 text-sm text-slate-500">Loading setup guide...</div>;
  return <div className="space-y-4"><div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4"><div className="flex items-center justify-between mb-1"><h2 className="text-sm font-semibold text-white">Environment Variables</h2><span className="text-[10px] font-mono text-slate-600 bg-white/[0.03] border border-white/[0.06] px-2 py-0.5 rounded">.env.example</span></div><p className="text-xs text-slate-500 mb-4">Copy <span className="font-mono text-slate-400">.env.example</span> to <span className="font-mono text-slate-400">.env</span> and fill in your own values — never commit real credentials.</p><div className="space-y-1">{data.environmentVariables.map((env) => <div key={env.key} className="flex items-center gap-3 py-2 px-3 rounded-md hover:bg-white/[0.03] border border-transparent hover:border-white/[0.06] transition-all"><span className="font-mono text-[11px] text-sky-400 w-44 shrink-0">{env.key}</span><span className="font-mono text-[11px] text-slate-600 flex-1 truncate italic">{env.value}</span>{env.required ? <span className="text-[9px] px-1.5 py-0.5 rounded bg-red-500/10 border border-red-500/25 text-red-400 font-mono">required</span> : <span className="text-[9px] px-1.5 py-0.5 rounded bg-slate-700/50 border border-white/[0.06] text-slate-500 font-mono">optional</span>}</div>)}</div></div><div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4"><h3 className="text-sm font-semibold text-white mb-3">Prerequisites</h3><div className="grid grid-cols-2 gap-2">{data.prerequisites.map((item) => <div key={item.name} className="flex items-center gap-2 p-2.5 rounded-md bg-white/[0.02] border border-white/[0.06]">{item.available ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : <Circle className="w-3.5 h-3.5 text-slate-600" />}<span className="text-xs text-slate-300">{item.name}</span><span className="ml-auto text-[10px] font-mono text-slate-600">{item.version}</span></div>)}</div></div></div>;
}
